---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micropinger-server
  namespace: default
  labels:
    app: micropinger-server
spec:
  selector:
    matchLabels:
      app: micropinger-server
  template:
    metadata:
      labels:
        app: micropinger-server
    spec:
      containers:
        - name: micropinger-server
          image: jmbaksregistrygenwe.azurecr.io/micropinger:1.0
          args: 
            - micropinger
          env:
          - name: mode
            value: "server"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: micropinger-server
  namespace: default
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: micropinger-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000 
  type: LoadBalancer

